Mobile menu
marurevi/Portfolio pull request #10
Opened 2022-04-05 20:26 UTC by marurevi

## Mobile menu
In mobile, implement the following features:
- When the user clicks (or taps) the hamburger button, the mobile menu appears.
- When the user clicks (or taps) the close (X) button, the mobile menu disappears.
- When the user clicks (or taps) any of the mobile menu options, the mobile menu disappears.
- When the user clicks (or taps) any of the mobile menu options, a correct part of the page is displayed.

2022-04-05 20:38 UTC, micheaol commented on script.js
> +menuButton.addEventListener('click', menuDisplay);
Please ensure that you stick to the design as much as possible (your pop-up should have full width like the Figma design 
 and the margin between the menu item and the design) using [the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1).

Your Implementation | Figma Design
:---:|:---:
![image](https://user-images.githubusercontent.com/10332499/161844863-14721af5-f6b2-4996-88d6-e564a0999197.png)  | ![image](https://user-images.githubusercontent.com/10332499/161844620-5235317a-e897-4de8-a068-cae3a6f93150.png)

2022-04-06 03:20 UTC, medaminedev66 requested changes
Hi @marurevi 😃,

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- The menu design is great and matches the Figma design. Great job 👍

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-06 03:20 UTC, medaminedev66 commented on style.css
> +  }
- [ ] As the previous reviewer mentioned in the previous screenshot, the menu should cover the whole screen. I would recommend adding the `position: fixed`, `top: 0`, `right: 0`, `bottom: 0`, and `left:0` to make the menu fixed and not scrollable and cover the whole mobile screen.
- Your design:
<img width="536" alt="image" src="https://user-images.githubusercontent.com/77190203/161889067-1919efcb-0431-499d-b352-df16967f2ced.png">

2022-04-06 05:04 UTC, marurevi commented on style.css
> +  }
Indeed, the fixed position looks better. I didn't know how to fix it. Thanks

2022-04-06 05:09 UTC, medaminedev66 approved these changes
## Hi @marurevi, 

# Status: Approved ✔️
Your project is complete!  There is nothing else to say other than... it's time to merge it 🚢
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-06 05:09 UTC, medaminedev66 commented on style.css
> +  }
[OPTIONAL] The position of your menu is fixed and not scrollable, great job 👍. Let's make it better by adding `height: 100%` and removing `padding: 335px 0;` so your menu design covers the whole screen.

2022-04-06 05:27 UTC, merged