Popup window
marurevi/Portfolio pull request #11
Opened 2022-04-08 06:37 UTC by marurevi

## Mobile popup Windows
- Creation de popup windows.
- Creation of JavaScript array to store all of the information for all projects. 
- The projects section has been created dynamically using the information stored in that JavaScript object.

2022-04-08 06:58 UTC, Kingstalux reviewed
Hi @marurevi, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

![68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f644550476b6e5269456e6965632f67697068792e676966](https://user-images.githubusercontent.com/85113567/162381212-4366960e-bb3b-4711-b573-52353b7c8abe.gif)

## Invalid Code Review Request 🛑 

- [ ] You have submitted a project, that has failing linters checks. Kindly fix your Eslint linter and make sure it passes before submitting your project for a review 👍 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-04-09 01:09 UTC, codepantha requested changes
Hi @marurevi 👋, 

## STATUS: CHANGES REQUIRED ♻️ 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media1.giphy.com/media/z3piokwf0WPH81MOhu/giphy.gif"/>

### Things to highlight 💡 
- Meaningul commit messages
- Descriptive PR
- Beautiful UI

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-09 02:20 UTC, marurevi commented on index.html
>          <ul class="textProject">
![image](https://user-images.githubusercontent.com/92180054/162552612-5a590648-bfc5-411e-ae0a-778a94b526f0.png)
@codepantha Thank you for taking the time to review my code. However, kindly I ask you that explain a little more about the changes that I have to do to improve my code. As you can see, I created a constructor to build the different cards. If you console log in to the projects array you will see the card that you mention before. I build the same card 6 times because that was the template but you still can access and modify the card that you wish and if you have a different project you only have to use the class Card (name, title, description, featuredimage, technologies, linkLiveVersion, link source).

2022-04-09 02:25 UTC, marurevi commented on popupWindows.js
> +
![image](https://user-images.githubusercontent.com/92180054/162553036-9fa7b2e3-7f67-47b9-a187-2cd7d6fd5ef0.png)
@codepantha I'm sorry for that. in my computer this is how it looks. Could you kindly give me some suggestions to fix the issue. In my laptop it's responsive... Thanks

2022-04-09 03:40 UTC, smunozmo approved these changes
Hi @marurevi , 👋 

Your project is complete!  There is nothing else to say other than... it's time to merge it! 🚀 
Very nice work, congratulations! 🎉 

### APPROVED! 👏 👏 👏 

<img src="https://media4.giphy.com/media/cFkiFMDg3iFoI/giphy.gif"/>

Cheers and Happy coding! 🤓 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

✅  Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-09 03:40 UTC, smunozmo commented on popupWindows.js
> +
[OPTIONAL] You are creating the projects array using a loop, this is actually clever and it works, but in the future, the goal is to create it manually for learning purposes because this way you will be able to edit a single project item.

2022-04-09 04:16 UTC, marurevi commented on popupWindows.js
> +
Yeah, I understand what you mean by creating it manually. I only use a loop because it was the same card but you also can build an object like card7 = new Card( 'card7', 'new project', 'description of it', 'src img', 'link1', 'link2') and then projects.push(card7). Or even modify the title with card7['title']='new project name'. 
Anyway thanks for taking the time to watch it and give me the feedback. Now I'm intrigued and I will try to build it in a different way.

2022-04-09 04:18 UTC, merged

2022-04-09 04:29 UTC, smunozmo commented on popupWindows.js
> +
@marurevi I agree, in this case, it was a smarter way to use a loop. 💯